// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVkOfsJnSlwO9lKiIsGNSJTNZBuTqgZqg',
    appId: '1:325224160597:web:eb8d930b446c0b899323dc',
    messagingSenderId: '325224160597',
    projectId: 'flutter-full-news-e3c09',
    authDomain: 'flutter-full-news-e3c09.firebaseapp.com',
    storageBucket: 'flutter-full-news-e3c09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApvjYEVeMnWZFQQuusbWxIO2vQcZkNbKw',
    appId: '1:325224160597:android:c61a0eb9cd4b80899323dc',
    messagingSenderId: '325224160597',
    projectId: 'flutter-full-news-e3c09',
    storageBucket: 'flutter-full-news-e3c09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtg0pugbPd84kBJRj6vkwAcBjKqDJU63k',
    appId: '1:325224160597:ios:ba272a425ba4aae59323dc',
    messagingSenderId: '325224160597',
    projectId: 'flutter-full-news-e3c09',
    storageBucket: 'flutter-full-news-e3c09.appspot.com',
    iosClientId: '325224160597-tqc08bn1r6en59shh018tniokrsvtk6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtg0pugbPd84kBJRj6vkwAcBjKqDJU63k',
    appId: '1:325224160597:ios:dd58a1d90495543d9323dc',
    messagingSenderId: '325224160597',
    projectId: 'flutter-full-news-e3c09',
    storageBucket: 'flutter-full-news-e3c09.appspot.com',
    iosClientId: '325224160597-10ojkmel6g4tlnonugc5s8e47tsk31ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseNewsApp.RunnerTests',
  );
}
